SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  email TEXT
);

DROP TABLE IF EXISTS calendars CASCADE;
CREATE TABLE calendars (
  id SERIAL PRIMARY KEY,
  creator BIGINT UNSIGNED NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  timeout INTEGER NOT NULL DEFAULT 1000,
  minDaysBetweenSameTopicExams INTEGER NOT NULL DEFAULT 14,
  minDaysBetweenSameYearExams INTEGER NOT NULL DEFAULT 2,
  difficultyPenalty FLOAT NOT NULL DEFAULT 1.0,
  startingDate DATE NOT NULL,
  normalSeasonDuration INTEGER NOT NULL DEFAULT 21,
  appealSeasonDuration INTEGER NOT NULL DEFAULT 14,
  spreadPenalty FLOAT NOT NULL DEFAULT 10.0,
  enqueueingTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  startTime TIMESTAMP,
  endTime TIMESTAMP
);

DROP TABLE IF EXISTS professors CASCADE;
CREATE TABLE professors (
  id SERIAL PRIMARY KEY,
  calendars BIGINT UNSIGNED NOT NULL REFERENCES calendars(id) ON DELETE CASCADE,
  name TEXT,
  acronym TEXT NOT NULL,
  cod TEXT
);

DROP TABLE IF EXISTS topics CASCADE;
CREATE TABLE topics (
  id SERIAL PRIMARY KEY,
  calendar BIGINT UNSIGNED NOT NULL REFERENCES calendars(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  acronym TEXT NOT NULL,
  code TEXT NOT NULL,
  year INTEGER NOT NULL,
  difficulty INTEGER NOT NULL DEFAULT 2,
  CONSTRAINT chk_difficulty CHECK (difficulty BETWEEN 1 AND 3)
);

DROP TABLE IF EXISTS topicProfessor CASCADE;
CREATE TABLE topicProfessor (
  id SERIAL PRIMARY KEY,
  topic BIGINT UNSIGNED NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
  professor BIGINT UNSIGNED NOT NULL REFERENCES professors(id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS exams CASCADE;
CREATE TABLE exams (
  id SERIAL PRIMARY KEY,
  calendar BIGINT UNSIGNED NOT NULL REFERENCES calendars(id) ON DELETE CASCADE,
  topic BIGINT UNSIGNED NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
  normal BOOLEAN NOT NULL DEFAULT TRUE,
  pc BOOLEAN NOT NULL DEFAULT FALSE,
  day DATE,
  time INT
);

DROP TABLE IF EXISTS students CASCADE;
CREATE TABLE students (
  id SERIAL PRIMARY KEY,
  calendar BIGINT UNSIGNED NOT NULL REFERENCES calendars(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  cod TEXT NOT NULL,
  entryYear INTEGER,
  currentYear INTEGER
);

DROP TABLE IF EXISTS studentTopic CASCADE;
CREATE TABLE studentTopic (
  student BIGINT UNSIGNED NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  topic BIGINT UNSIGNED NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
  PRIMARY KEY (student, topic)
);

DROP TABLE IF EXISTS rooms CASCADE;
CREATE TABLE rooms (
  id SERIAL PRIMARY KEY,
  calendar BIGINT UNSIGNED NOT NULL REFERENCES calendars(id) ON DELETE CASCADE,
  cod TEXT NOT NULL,
  capacity INTEGER NOT NULL,
  pc BOOLEAN NOT NULL
);

DROP TABLE IF EXISTS professorUnavailable CASCADE;
CREATE TABLE professorUnavailable (
  id SERIAL PRIMARY KEY,
  calendar BIGINT UNSIGNED NOT NULL REFERENCES calendars(id) ON DELETE CASCADE,
  professor BIGINT UNSIGNED NOT NULL REFERENCES professors(id) ON DELETE CASCADE,
  day DATE NOT NULL,
  time INTEGER NOT NULL,
  UNIQUE(professor, day, time)
);

DROP TABLE IF EXISTS roomPeriodUnavailable CASCADE;
CREATE TABLE roomPeriodUnavailable (
  id SERIAL PRIMARY KEY,
  creator BIGINT UNSIGNED NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  room BIGINT UNSIGNED NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
  day DATE NOT NULL,
  time INT NOT NULL
);

SET FOREIGN_KEY_CHECKS=1;